"""initial schema

Revision ID: 2b84072c7df3
Revises: 
Create Date: 2026-08-18 22:50:24.066855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b84072c7df3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wiki_title', sa.String(length=255), nullable=False),
    sa.Column('wiki_pageid', sa.Integer(), nullable=False),
    sa.Column('display_title', sa.String(length=255), nullable=False),
    sa.Column('slot_pattern', sa.JSON(), nullable=False),
    sa.Column('summary_extract', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready', 'scheduled', 'retired', name='article_status'), server_default='draft', nullable=False),
    sa.Column('difficulty_tier', sa.SmallInteger(), nullable=True),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wiki_pageid'),
    sa.UniqueConstraint('wiki_title')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('ix_articles_status', ['status'], unique=False)

    op.create_table('pool_alert_state',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('low_pool_alert_active', sa.Boolean(), nullable=False),
    sa.Column('last_remaining_count', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_alert_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('title_resolutions',
    sa.Column('normalized_guess', sa.String(length=255), nullable=False),
    sa.Column('resolved_pageid', sa.Integer(), nullable=True),
    sa.Column('resolved_title', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('normalized_guess')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wikimedia_sub', sa.String(length=64), nullable=False),
    sa.Column('wikimedia_username', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wikimedia_sub')
    )
    op.create_table('clues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('clue_type', sa.Enum('commons_image', 'dyk_or_notable_fact', 'wikidata_fact', 'infobox_fact', 'categories', 'etymology', 'wikisource_excerpt', 'wikivoyage_fact', 'pageviews', 'top_citation', 'incoming_links', 'long_section_title', 'creation_year', 'langlinks_count', name='clue_type'), nullable=False),
    sa.Column('reveal_rank_hint', sa.SmallInteger(), nullable=False),
    sa.Column('clue_text', sa.Text(), nullable=False),
    sa.Column('clue_media_url', sa.String(length=1024), nullable=True),
    sa.Column('clue_payload', sa.JSON(), nullable=True),
    sa.Column('is_title_leaking', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clues', schema=None) as batch_op:
        batch_op.create_index('ix_clues_article_id', ['article_id'], unique=False)

    op.create_table('daily_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_date', sa.Date(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('clue_order', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id'),
    sa.UniqueConstraint('challenge_date')
    )
    with op.batch_alter_table('daily_challenges', schema=None) as batch_op:
        batch_op.create_index('ix_daily_challenges_date', ['challenge_date'], unique=False)

    op.create_table('link_cache_meta',
    sa.Column('answer_article_id', sa.Integer(), nullable=False),
    sa.Column('max_depth_precomputed', sa.SmallInteger(), nullable=False),
    sa.Column('node_cap', sa.Integer(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'complete', 'capped', 'failed', name='link_cache_status'), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['answer_article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_article_id')
    )
    op.create_table('link_cache_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_article_id', sa.Integer(), nullable=False),
    sa.Column('node_pageid', sa.Integer(), nullable=False),
    sa.Column('node_title', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.SmallInteger(), nullable=False),
    sa.Column('discovered_via', sa.Enum('precompute', 'live_bfs', name='link_cache_discovered_via'), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_article_id', 'node_pageid', name='uq_link_cache_answer_node')
    )
    with op.batch_alter_table('link_cache_nodes', schema=None) as batch_op:
        batch_op.create_index('ix_link_cache_answer_degree', ['answer_article_id', 'degree'], unique=False)
        batch_op.create_index('ix_link_cache_node_title', ['node_title'], unique=False)

    op.create_table('user_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('games_won', sa.Integer(), nullable=False),
    sa.Column('win_distribution', sa.JSON(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('max_streak', sa.Integer(), nullable=False),
    sa.Column('last_played_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_challenge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anon_token', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'won', 'lost', name='game_session_status'), nullable=False),
    sa.Column('clues_revealed', sa.SmallInteger(), nullable=False),
    sa.Column('guesses_made', sa.SmallInteger(), nullable=False),
    sa.Column('solved_on_guess_number', sa.SmallInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_challenge_id'], ['daily_challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'daily_challenge_id', name='uq_session_user_challenge')
    )
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_anon_challenge', ['anon_token', 'daily_challenge_id'], unique=False)
        batch_op.create_index('ix_sessions_challenge', ['daily_challenge_id'], unique=False)

    op.create_table('guess_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.SmallInteger(), nullable=False),
    sa.Column('raw_guess_text', sa.String(length=255), nullable=False),
    sa.Column('resolved_title', sa.String(length=255), nullable=True),
    sa.Column('resolved_pageid', sa.Integer(), nullable=True),
    sa.Column('lexical_score_bucket', sa.SmallInteger(), nullable=False),
    sa.Column('lexical_score_raw', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('degrees_value', sa.SmallInteger(), nullable=True),
    sa.Column('degrees_capped', sa.Boolean(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guess_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_guess_attempts_session', ['game_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guess_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_guess_attempts_session')

    op.drop_table('guess_attempts')
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_challenge')
        batch_op.drop_index('ix_sessions_anon_challenge')

    op.drop_table('game_sessions')
    op.drop_table('user_stats')
    with op.batch_alter_table('link_cache_nodes', schema=None) as batch_op:
        batch_op.drop_index('ix_link_cache_node_title')
        batch_op.drop_index('ix_link_cache_answer_degree')

    op.drop_table('link_cache_nodes')
    op.drop_table('link_cache_meta')
    with op.batch_alter_table('daily_challenges', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_challenges_date')

    op.drop_table('daily_challenges')
    with op.batch_alter_table('clues', schema=None) as batch_op:
        batch_op.drop_index('ix_clues_article_id')

    op.drop_table('clues')
    op.drop_table('users')
    op.drop_table('title_resolutions')
    op.drop_table('pool_alert_state')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_status')

    op.drop_table('articles')
    # ### end Alembic commands ###
