"""drop articles.difficulty_tier

Revision ID: b4e6d29a7f31
Revises: a3d7c9f1e6b2
Create Date: 2026-08-29 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e6d29a7f31'
down_revision = 'a3d7c9f1e6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('difficulty_tier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty_tier', sa.SmallInteger(), nullable=True))

    # ### end Alembic commands ###
